USE [master]
GO

/****** Object:  Database [F18_ksmmcquad]    Script Date: 12/9/2018 9:59:14 PM ******/
CREATE DATABASE [F18_ksmmcquad]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'F18_ksmmcquad', FILENAME = N'D:\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\F18_ksmmcquad.mdf' , SIZE = 1048576KB , MAXSIZE = 2097152KB , FILEGROWTH = 256KB )
 LOG ON 
( NAME = N'F18_ksmmcquad_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\F18_ksmmcquad_log.mdf' , SIZE = 768KB , MAXSIZE = 512000KB , FILEGROWTH = 10%)
GO

ALTER DATABASE [F18_ksmmcquad] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [F18_ksmmcquad].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [F18_ksmmcquad] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET ARITHABORT OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [F18_ksmmcquad] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [F18_ksmmcquad] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET  ENABLE_BROKER 
GO

ALTER DATABASE [F18_ksmmcquad] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [F18_ksmmcquad] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET RECOVERY FULL 
GO

ALTER DATABASE [F18_ksmmcquad] SET  MULTI_USER 
GO

ALTER DATABASE [F18_ksmmcquad] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [F18_ksmmcquad] SET DB_CHAINING OFF 
GO

ALTER DATABASE [F18_ksmmcquad] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [F18_ksmmcquad] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [F18_ksmmcquad] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [F18_ksmmcquad] SET  READ_WRITE 
GO


